### ISSUE TITLE
Add 'switch' as a snippet

### ISSUE THREAD

**Issue by katrinkerber** [BarrelStrength/Craft-Twig.tmbundle#10]
Would be great if `switch` could be a tab trigger to output:

```
{% switch condition %} ... {% endswitch %}
```

**Comment by BenParizek** [comment]
Thanks Katrin.  I'll be sure to get this in the next version. Working on releasing it soon!

**Comment by BenParizek** [comment]
The next release will have a switch tab trigger like below, with tab stops at the _variable_ and _values_:

``` twig
{% switch variable %}

	{% case "value1" %}
	

	{% case "value2" %}
	

	{% default %}
	

{% endswitch %}```

**Comment by BenParizek** [comment]
This is now released: https://github.com/BarrelStrength/Craft-Twig.tmbundle/releases

**Comment by katrinkerber** [comment]
That's brilliant, thank you Ben.

I've just tried to upgrade in Sublime, but I am getting this error:

> Error loading syntax file "Packages/Craft-Twig/Syntaxes/HTML (Twig).tmLanguage": Error parsing plist xml: Failed to open file In file "Packages/Craft-Twig/Syntaxes/HTML (Twig).tmLanguage"

**Comment by BenParizek** [comment]
Hey Katrin,

I think this is just a cache or session issue due to some name changes in the underlying files.  Can you try to: 
1) Uninstall your previous version of Craft-Twig
2) Remove any cached version of Craft-Twig in `~/Library/Application\ Support/Sublime\ Text\ 3/Cache/
3) Clear the sublime session in in `~/Library/Application\ Support/Sublime\ Text\ 3/Local/Session.sublime_session
4) Reinstall the Craft-Twig package

**Comment by katrinkerber** [comment]
That worked a treat, thank you very much Ben :)
